main:
  steps:
    - extract_properties:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/extract-opa-properties"
          auth:
            type: OIDC
          timeout: 540

    - prepare_properties:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/prepare-opa-properties"
          auth:
            type: OIDC
          timeout: 540

    - load_properties:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/load-opa-properties"
          auth:
            type: OIDC
          timeout: 540

    - extract_assessments:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/extract-opa-assessments"
          auth:
            type: OIDC
          timeout: 540

    - prepare_assessments:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/prepare-opa-assessments"
          auth:
            type: OIDC
          timeout: 540

    - load_assessments:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/load-opa-assessments"
          auth:
            type: OIDC
          timeout: 540

    - extract_parcels:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/extract-pwd-parcels"
          auth:
            type: OIDC
          timeout: 540

    - prepare_parcels:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/prepare-pwd-parcels"
          auth:
            type: OIDC
          timeout: 540

    - load_parcels:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/load-pwd-parcels"
          auth:
            type: OIDC
          timeout: 540

    - transform_tax_year_assessment_bins:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/transform-tax-year-assessment-bins"
          auth:
            type: OIDC
          timeout: 540

    - transform_current_assessment_bins:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/transform-current-assessment-bins"
          auth:
            type: OIDC
          timeout: 540

    - transform_current_assessments_model_training_data:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/transform-current-assessments-model-training-data"
          auth:
            type: OIDC
          timeout: 540

- generate_assessment_bins:
          call: http.get
          args:
            url: "https://us-central1-musa5090s26-team6.cloudfunctions.net/generate-assessment-bins"
            timeout: 540

      - generate_assessment_chart_configs:
          call: http.get
          args:
            url: "https://us-central1-musa5090s26-team6.cloudfunctions.net/generate-assessment-chart-configs"
            timeout: 540

      - export_assessment_chart_configs:
          call: http.get
          args:
            url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/export-assessment-chart-configs"
            auth:
              type: OIDC
          timeout: 540

    - export_property_tile_info:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/export-property-tile-info"
          auth:
            type: OIDC
          timeout: 540

    - generate_tile_style_metadata:
        call: http.get
        args:
          url: "https://us-east4-musa5090s26-team6.cloudfunctions.net/generate-tile-style-metadata"
          auth:
            type: OIDC
          timeout: 540

    - generate_property_map_tiles:
        call: http.post
        args:
          url: "https://us-east4-run.googleapis.com/v2/projects/musa5090s26-team6/locations/us-east4/jobs/generate-property-map-tiles:run"
          auth:
            type: OAuth2
          timeout: 1800
